version: 0.0

os: linux

files:
  - source: target/workshop-0.0.1-SNAPSHOT.jar
    destination: /opt/workshop

hooks:

  ApplicationStop:
    - location: scripts/stop.sh

  BeforeInstall:
    - location: scripts/before-install.sh

  ApplicationStart:
    - location: scripts/start.sh

  ValidateService:
    - location: scripts/validate.sh
